import { v4 as uuidv4 } from 'uuid';

import { MakeCertParam } from '../types/GeneralType';

export default function makeCert(data: MakeCertParam) {
  const {
    organization,
    subOrganization,
    certType,
    builder,
    owner,
    certNumber,
    issuedDate,
    expireDate,
    measureDate,
    country,
    sailNumber,
    boatName,
    className,
    beam,
    draft,
    displacement,
    extras,
    hasPolars,
    polars,
    hasTimeAllowances,
    timeAllowances,
    originalId,
  } = data;
  return {
    syrf_id: uuidv4(),
    organization,
    sub_organization: subOrganization,
    cert_type: certType,
    builder,
    owner: owner || null,
    cert_number: certNumber,
    issued_date: issuedDate ? new Date(issuedDate) : null,
    expire_date: expireDate ? new Date(expireDate) : null,
    measure_date: measureDate ? new Date(measureDate) : null,
    country,
    sail_number: sailNumber,
    boat_name: boatName,
    class_name: className,
    beam: beam || null,
    draft: draft || null,
    displacement: displacement || null,
    extras,
    has_polars: hasPolars,
    polars,
    has_time_allowances: hasTimeAllowances,
    time_allowances: timeAllowances,
    original_id: originalId,
  };
}
